export const TEST_LIST_REQUEST = "TEST_LIST_REQUEST";
export const TEST_LIST_SUCCESS = "TEST_LIST_SUCCESS";
export const TEST_LIST_FAIL = "TEST_LIST_FAIL";

export const TEST_DETAILS_REQUEST = "TEST_DETAILS_REQUEST";
export const TEST_DETAILS_SUCCESS = "TEST_DETAILS_SUCCESS";
export const TEST_DETAILS_FAIL = "TEST_DETAILS_FAIL";

export const COUNT_REQUEST = "COUNT_REQUEST";
export const COUNT_SUCCESS = "COUNT_SUCCESS";
export const COUNT_FAIL = "COUNT_FAIL";
