# Generated by Django 3.2.7 on 2021-10-22 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('oncho', models.IntegerField(blank=True, null=True)),
                ('schisto', models.IntegerField(blank=True, null=True)),
                ('lf', models.IntegerField(blank=True, null=True)),
                ('helminths', models.IntegerField(blank=True, null=True)),
                ('onchoImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('schistoImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('lfImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('helminthsImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
